version: '3.8'

services:
  api:
    image: ghcr.io/esportbrande/api-intranet:sha-9735b64
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
    env_file:
      - .env
    volumes:
      - ./host_secrets.json:/etc/secrets/host.json:ro